### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by softmarshmallow** [danbovey/react-infinite-scroller#306]
With NextJS, InfiniteScroll throws unrelatable warning.

```
Check the render method of `InfiniteScroll`. It was passed a child from Page. See https://reactjs.org/link/warning-keys for more information.
    at InfiniteScroll (webpack-internal:///../node_modules/react-infinite-scroller/dist/InfiniteScroll.js:31:5)
    at main
    at eval (webpack-internal:///../node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
```

```tsx
function Demo(){
    // .....
    return (
        <InfiniteScroll
          pageStart={pageStart}
          hasMore={data.hasMore}
          loadMore={() => {
            if (data.loading) return;
            update.loadMore();
          }}
          useWindow={false}
          getScrollParent={() => document.querySelector("body")}
          loader={
            <>
              {data.loading && (
                <div className="loader" key={0}>
                  Loading ...
                </div>
              )}
            </>
          }
        >
          <div className="grid" key="grid">
            {data.files.map((file) => (
              <Link
                key={file.id}
                href={{
                  pathname: "/community/file/[id]",
                  query: {
                    id: file.id,
                  },
                }}
              >
                <div>
                  <FileCard {...file} />
                </div>
              </Link>
            ))}
          </div>
        </InfiniteScroll>
    )
}
```

**Comment by softmarshmallow** [comment]
Ansering myself.

You can't have empty fragment as a loader. 

Key Warning
```tsx
<InfiniteScroll
       loader={
            <>
              {data.loading && (
                <div className="loader" key={0}>
                  Loading ...
                </div>
              )}
            </>
          }
>
```

Fixed
```tsx
<InfiniteScroll
       loader={
              data.loading && (
                <div className="loader" key={0}>
                  Loading ...
                </div>
              )
          }
>
```


ref: https://github.com/oVirt/ovirt-web-ui/issues/562#issuecomment-560259549
